# Generated by Django 6.0.3 on 2026-06-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_addressmodel_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
