# Generated by Django 6.0.4 on 2026-06-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_addressmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
