# Generated by Django 6.0.3 on 2026-05-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
