# Generated by Django 6.0.3 on 2026-05-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorys', 'verbose_name_plural': 'Categories'},
        ),
    ]
