# Generated by Django 6.0.4 on 2026-08-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoice_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='refund_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=250, unique=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_receipt', models.CharField(max_length=200)),
                ('refund_currency', models.CharField(max_length=250)),
                ('refund_payment_id', models.CharField(max_length=100)),
                ('refund_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refund_status', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
