# Generated by Django 6.0.4 on 2026-08-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_refund_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='refund_model',
            new_name='refund',
        ),
    ]
